language: python

before_install:
- "pip install -U pip"
- "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
- pip install -r requirements.txt

script:
- python -m unittest

after-success:
- coverage run -m unittest
- coveralls
