language: python

before_install:
- "pip install -U pip"
- "export PYTHONPATH=$PYTHONPATH:$(/Users/chelsea/201)"

install:
- pip install -r requirements.txt
- pip install pytest-cov
- pip install coveralls

script:
- python --cov

after-success:
- coverage run -m unittest
- coveralls
